In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import svm, preprocessing

In [2]:
#testar dataset já com procrustes
name = '/home/walter/Documents/ruttner/detections_with_procrustes.csv'
file = pd.read_csv(name,header=None,sep='\t')
file.head()

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,0.007939,-0.354441,0.014043,-0.383106,-0.057594,-0.340485,-0.179494,-0.285798,-0.226862,-0.244240,...,-0.345042,-0.533943,-0.337241,-0.589270,-0.404797,-0.627989,-0.403976,-0.816200,-0.305953,0
1,-0.001419,-0.363799,0.004685,-0.392464,-0.066952,-0.349843,-0.188851,-0.295156,-0.236220,-0.253598,...,-0.354400,-0.543301,-0.346599,-0.598628,-0.414155,-0.637347,-0.413334,-0.825558,-0.315311,0
2,-0.002576,-0.364957,0.003527,-0.393622,-0.068110,-0.351001,-0.190009,-0.296314,-0.237378,-0.254756,...,-0.355558,-0.544459,-0.347757,-0.599785,-0.415313,-0.638505,-0.414492,-0.826716,-0.316469,0
3,-0.000830,-0.363211,0.005273,-0.391876,-0.066364,-0.349255,-0.188263,-0.294568,-0.235632,-0.253009,...,-0.353812,-0.542713,-0.346011,-0.598039,-0.413567,-0.636759,-0.412745,-0.824970,-0.314723,0
4,0.004736,-0.357645,0.010840,-0.386309,-0.060798,-0.343688,-0.182697,-0.289001,-0.230066,-0.247443,...,-0.348245,-0.537146,-0.340445,-0.592473,-0.408001,-0.631193,-0.407179,-0.819403,-0.309157,0

In [3]:
y = file[38]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: 38, dtype: int64

In [4]:
X = file.drop([38],axis=1)
X.head()

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
0,0.007939,-0.354441,0.014043,-0.383106,-0.057594,-0.340485,-0.179494,-0.285798,-0.226862,-0.244240,...,-0.529128,-0.345042,-0.533943,-0.337241,-0.589270,-0.404797,-0.627989,-0.403976,-0.816200,-0.305953
1,-0.001419,-0.363799,0.004685,-0.392464,-0.066952,-0.349843,-0.188851,-0.295156,-0.236220,-0.253598,...,-0.538486,-0.354400,-0.543301,-0.346599,-0.598628,-0.414155,-0.637347,-0.413334,-0.825558,-0.315311
2,-0.002576,-0.364957,0.003527,-0.393622,-0.068110,-0.351001,-0.190009,-0.296314,-0.237378,-0.254756,...,-0.539643,-0.355558,-0.544459,-0.347757,-0.599785,-0.415313,-0.638505,-0.414492,-0.826716,-0.316469
3,-0.000830,-0.363211,0.005273,-0.391876,-0.066364,-0.349255,-0.188263,-0.294568,-0.235632,-0.253009,...,-0.537897,-0.353812,-0.542713,-0.346011,-0.598039,-0.413567,-0.636759,-0.412745,-0.824970,-0.314723
4,0.004736,-0.357645,0.010840,-0.386309,-0.060798,-0.343688,-0.182697,-0.289001,-0.230066,-0.247443,...,-0.532331,-0.348245,-0.537146,-0.340445,-0.592473,-0.408001,-0.631193,-0.407179,-0.819403,-0.309157

In [5]:
X.describe()

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
count,7.319000e+03,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000,...,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000,7319.000000
mean,-5.441476e-07,-0.362381,0.006103,-0.391046,-0.065534,-0.348425,-0.187433,-0.293738,-0.234802,-0.252180,...,-0.537067,-0.352982,-0.541883,-0.345181,-0.597209,-0.412737,-0.635929,-0.411916,-0.824140,-0.313893
std,8.788430e-03,0.008788,0.008788,0.008788,0.008788,0.008788,0.008788,0.008788,0.008788,0.008788,...,0.008788,0.008788,0.008788,0.008788,0.008788,0.008788,0.008788,0.008788,0.008788,0.008788
min,-5.861664e-02,-0.420997,-0.052513,-0.449662,-0.124150,-0.407041,-0.246049,-0.352354,-0.293418,-0.310796,...,-0.595684,-0.411598,-0.600499,-0.403797,-0.655826,-0.471353,-0.694545,-0.470532,-0.882756,-0.372509
25%,-3.577150e-03,-0.365958,0.002527,-0.394622,-0.069111,-0.352002,-0.191010,-0.297315,-0.238379,-0.255756,...,-0.540644,-0.356559,-0.545460,-0.348758,-0.600786,-0.416314,-0.639506,-0.415492,-0.827717,-0.317470
50%,5.021130e-04,-0.361878,0.006606,-0.390543,-0.065032,-0.347922,-0.186931,-0.293235,-0.234300,-0.251677,...,-0.536565,-0.352479,-0.541380,-0.344678,-0.596707,-0.412234,-0.635426,-0.411413,-0.823637,-0.313391
75%,4.309885e-03,-0.358071,0.010414,-0.386735,-0.061224,-0.344115,-0.183123,-0.289428,-0.230492,-0.247869,...,-0.532757,-0.348671,-0.537573,-0.340871,-0.592899,-0.408427,-0.631619,-0.407605,-0.819830,-0.309583
max,1.879446e-01,-0.174436,0.194049,-0.203101,0.122411,-0.160480,0.000512,-0.105793,-0.046857,-0.064234,...,-0.349122,-0.165037,-0.353938,-0.157236,-0.409264,-0.224792,-0.447984,-0.223970,-0.636195,-0.125948

In [6]:
df_norm = X[[30]]
df_norm = (df_norm - df_norm.min()) / (df_norm.max() - df_norm.min())
df_norm.head()

         30
0  0.269936
1  0.231983
2  0.227287
3  0.234369
4  0.256945

In [7]:
#testar sem procrustes
name = '/home/walter/Documents/ruttner/detections_no_procrustes.csv'
file = pd.read_csv(name,header=None,sep='\t')
y = file[38]
X = file.drop([38],axis=1)
X = X.as_matrix()
X = np.reshape(X, (-1,19,2))
file.head()

/home/walter/anaconda3/envs/w/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,78.0,202.0,73.0,218.0,96.0,200.0,142.0,178.0,157.0,164.0,...,177.0,264.0,206.0,284.0,219.0,299.0,218.0,365.0,185.0,0
1,68.0,201.0,63.0,214.0,94.0,198.0,138.0,178.0,155.0,163.0,...,178.0,262.0,207.0,284.0,221.0,301.0,222.0,368.0,185.0,0
2,77.0,202.0,72.0,217.0,101.0,198.0,141.0,180.0,156.0,165.0,...,178.0,264.0,206.0,283.0,219.0,296.0,220.0,359.0,184.0,0
3,72.0,203.0,68.0,216.0,95.0,199.0,139.0,178.0,156.0,163.0,...,207.0,271.0,178.0,287.0,220.0,301.0,219.0,366.0,183.0,0
4,79.0,202.0,76.0,218.0,100.0,199.0,140.0,179.0,158.0,163.0,...,178.0,261.0,207.0,282.0,221.0,296.0,221.0,359.0,186.0,0

In [8]:
X[0]

array([[ 78., 202.],
       [ 73., 218.],
       [ 96., 200.],
       [142., 178.],
       [157., 164.],
       [164., 253.],
       [172., 212.],
       [171., 235.],
       [180., 186.],
       [195., 195.],
       [201., 158.],
       [204., 169.],
       [225., 175.],
       [255., 248.],
       [266., 177.],
       [264., 206.],
       [284., 219.],
       [299., 218.],
       [365., 185.]])

In [9]:
df_norm = np.reshape(X, (-1,38))
df_norm = (df_norm - df_norm.min()) / (df_norm.max() - df_norm.min())
for x in range(7):
    print(df_norm[x*1000])

[0.16883117 0.49090909 0.15584416 0.53246753 0.21558442 0.48571429
 0.33506494 0.42857143 0.37402597 0.39220779 0.39220779 0.62337662
 0.41298701 0.51688312 0.41038961 0.57662338 0.43376623 0.44935065
 0.47272727 0.47272727 0.48831169 0.37662338 0.4961039  0.40519481
 0.55064935 0.42077922 0.62857143 0.61038961 0.65714286 0.42597403
 0.65194805 0.5012987  0.7038961  0.53506494 0.74285714 0.53246753
 0.91428571 0.44675325]
[0.14805195 0.48571429 0.13766234 0.52467532 0.21298701 0.48051948
 0.32467532 0.43116883 0.36623377 0.39220779 0.38701299 0.62857143
 0.41558442 0.52207792 0.41038961 0.58441558 0.43116883 0.44935065
 0.48571429 0.37662338 0.48051948 0.48051948 0.4961039  0.40779221
 0.55584416 0.42337662 0.63636364 0.62077922 0.65454545 0.42857143
 0.65714286 0.5038961  0.71168831 0.53766234 0.75064935 0.53506494
 0.92207792 0.44155844]
[0.14545455 0.48571429 0.13246753 0.52727273 0.21298701 0.47792208
 0.32207792 0.42597403 0.36623377 0.38701299 0.38441558 0.63116883
 0.41558442 0.51948052 0.40779221 0.58181818 0.43376623 0.44675325
 0.48571429 0.37402597 0.48051948 0.47792208 0.4961039  0.40779221
 0.55584416 0.42337662 0.63896104 0.61818182 0.66233766 0.42597403
 0.65974026 0.50649351 0.71168831 0.53766234 0.75324675 0.53506494
 0.92727273 0.44155844]
[0.13506494 0.48831169 0.12207792 0.52727273 0.2025974  0.48311688
 0.31428571 0.43376623 0.36363636 0.39220779 0.36883117 0.62597403
 0.40519481 0.51948052 0.4        0.57662338 0.42597403 0.44935065
 0.47532468 0.37402597 0.46753247 0.47792208 0.48571429 0.40779221
 0.54545455 0.42077922 0.63116883 0.62077922 0.65974026 0.42857143
 0.65194805 0.5038961  0.70909091 0.54025974 0.74805195 0.54025974
 0.92207792 0.44415584]
[0.15844156 0.48571429 0.15064935 0.52467532 0.21298701 0.48051948
 0.33506494 0.42597403 0.37142857 0.38701299 0.39220779 0.61818182
 0.41818182 0.51688312 0.41038961 0.57662338 0.43896104 0.44415584
 0.49090909 0.37662338 0.47792208 0.47532468 0.4987013  0.4025974
 0.56103896 0.42337662 0.64935065 0.4961039  0.64155844 0.61038961
 0.65454545 0.42857143 0.70909091 0.53506494 0.74545455 0.53246753
 0.90909091 0.44415584]
[0.15584416 0.48571429 0.14545455 0.52727273 0.21038961 0.48051948
 0.32987013 0.42077922 0.37142857 0.38441558 0.38441558 0.62597403
 0.42077922 0.51948052 0.41038961 0.58181818 0.43376623 0.44415584
 0.4961039  0.36883117 0.48571429 0.48051948 0.5038961  0.4
 0.56623377 0.42077922 0.64155844 0.62077922 0.67012987 0.42857143
 0.65714286 0.5038961  0.71948052 0.54285714 0.75324675 0.54025974
 0.91688312 0.43896104]
[0.14285714 0.52207792 0.16103896 0.48051948 0.23636364 0.47532468
 0.33246753 0.43116883 0.38701299 0.38961039 0.38441558 0.61818182
 0.4025974  0.57402597 0.41818182 0.52207792 0.44155844 0.45194805
 0.47012987 0.47792208 0.4961039  0.37402597 0.50909091 0.40779221
 0.56103896 0.42077922 0.62337662 0.61558442 0.64675325 0.5038961
 0.67012987 0.43116883 0.7038961  0.54285714 0.74025974 0.54285714
 0.91688312 0.45194805]

In [10]:
import procrustes_module as pr
X_, reference = pr.procrustes_analysis(X, 1300)

def ajust_reference(X, reference):
	X = np.reshape(X, (-1, 38))
	reference = np.reshape(reference, (-1, 38))
	
	result = []
	for x in X:
		number_list = []
		for index, ref in enumerate(reference):
			number_list.append(x[index] - ref)
		result.append(number_list)
	return result
		
X_ = ajust_reference(X_, reference)

[[ 74. 202.]
 [ 69. 217.]
 [ 96. 199.]
 [139. 178.]
 [155. 163.]
 [163. 254.]
 [174. 214.]
 [172. 239.]
 [179. 185.]
 [198. 156.]
 [195. 196.]
 [201. 169.]
 [222. 174.]
 [256. 251.]
 [267. 176.]
 [264. 206.]
 [289. 222.]
 [301. 221.]
 [367. 185.]]

In [11]:
X_ = np.reshape(X_, (-1,38))
X_ = pd.DataFrame(X_)
X_ = (X_ - X_.min()) / (X_.max() - X_.min())
X_.head()

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
0,0.239995,0.239995,0.239995,0.239995,0.239995,0.239995,0.239995,0.239995,0.239995,0.239995,...,0.239995,0.239995,0.239995,0.239995,0.239995,0.239995,0.239995,0.239995,0.239995,0.239995
1,0.202604,0.202604,0.202604,0.202604,0.202604,0.202604,0.202604,0.202604,0.202604,0.202604,...,0.202604,0.202604,0.202604,0.202604,0.202604,0.202604,0.202604,0.202604,0.202604,0.202604
2,0.188567,0.188567,0.188567,0.188567,0.188567,0.188567,0.188567,0.188567,0.188567,0.188567,...,0.188567,0.188567,0.188567,0.188567,0.188567,0.188567,0.188567,0.188567,0.188567,0.188567
3,0.215909,0.215909,0.215909,0.215909,0.215909,0.215909,0.215909,0.215909,0.215909,0.215909,...,0.215909,0.215909,0.215909,0.215909,0.215909,0.215909,0.215909,0.215909,0.215909,0.215909
4,0.217980,0.217980,0.217980,0.217980,0.217980,0.217980,0.217980,0.217980,0.217980,0.217980,...,0.217980,0.217980,0.217980,0.217980,0.217980,0.217980,0.217980,0.217980,0.217980,0.217980